### ISSUE TITLE
How to adjust covariates in DSS?

### ISSUE THREAD

**Issue by bishwaG** [haowulab/DSS#1]
Hi,
I have following experimental design(RRBS). I would like to do differential methylation analysis between group A and group B by correcting sample handling time. How can I do in DSS.

```
Sample	Group	handlingTime
S1	A	100
S2	A	152
S3	A	452
S4	A	1258
S5	B	214
S6	B	352
S7	B	574
S8	B	214
```
Regards,
BishwaG

**Comment by haowulab** [comment]
Do you want to treat the handlingTime as continuous variable? If so, you can use the DMLtest.multiFactor function, e.g., fit model using DMLfit.multiFactor with formula=~Group+ handlingTime, then test for Group.

**Comment by bishwaG** [comment]
Hi @haowulab,
I tried following, but I did not get meanMethy1, meanMethy2 and diff.Methy. I am doing something wrong?

```
rrbs <- makeBSseqData(data,sample)

## Model fitting
DMLfit <- DMLfit.multiFactor(rrbs, design = design.matrix, formula = ~Group+handlingTime)

## Performing test
DMLtest <- DMLtest.multiFactor(DMLfit, coef="Group")

dmr <- callDMR(DMLtest, p.threshold=0.05)

head(dmr)
#      chr   start     end length  nCG areaStat
# 33090  19  746868 1036109 289242 5740 496.6219
# 33089  19  397436  746571 349136 7249 466.3004
# 29      1 2014920 2259202 244283 3331 395.4669
# 33118  19 3258024 3473319 215296 2158 332.5129
# 25460  16 1914723 2177106 262384 4078 324.9172
# 63017   7  945805 1185955 240151 2920 306.5631



```

**Comment by haowulab** [comment]
There's nothing wrong. The output doesn't include meanMethy1, meanMethy2 and diff.Methy from DMLtest.multiFactor. This is a recurrent question. I should put this in the function help and vignette. In a general experimental design with multiple, possibly continuous covariate, it is no longer a simple two group test so there'll be no mean methylation levels and difference between two groups (represented by meanMethy1, meanMethy2 and diff.Methy). 

Hao

**Comment by bishwaG** [comment]
Is there a way to adjust covariates and also calculate group difference?

**Comment by haowulab** [comment]
No it'll be difficult from a general experimental design. The regression coefficient is something like “the change of Y with 1 unit increase of X, adjusting for other covariates”. Maybe your X is just two groups so one might be able to calculate the change of methylation between two groups, adjusting for other covariates. However from a software development point of view, I have to make it general and assume X can be anything (even continuous). That’s why it’s difficult to compute the relative methylation level.

**Comment by bishwaG** [comment]
Hi @haowulab,
Thank your for the details. I did multidimensional scaling (MDS) of my samples using site methylation levels, but did not find effect of `handlingTime` in MDS plot. This tells that I do not need to adjust the covariate `handlingTime`. Therefore, now I did two group test using `DMLtest()` both with/without smoothing. When I used `callDMR()` and I got `meanMethy1`, `meanMethy2`, `diff.Methyl,` but did not get pvalue/fdr.

One more question. How does DSS handle NAs. Does it remove sites if it has NAs in some of the samples?

**Comment by haowulab** [comment]
For the NAs: the CpG sites with some NAs will NOT be removed, as long as there are enough degree of freedom for the regression. For example, in a 3 vs. 3 two-group comparison, if there is one NA in each group for a CpG sites, the test can still be conducted and this CpG will not be removed.
