### ISSUE TITLE
results from DML calling using DSS with smoothing show non-CpG sites

### ISSUE THREAD

**Issue by Yuxinagli** [haowulab/DSS#17]
Hi,

Thank you very for providing DSS for the community.
I used DSS to call DMLs and DMRs with following code:

library(DSS)
library(bsseq)
dat.list = list()
for(i in 1:12){
    spl=paste0("wgbs_",i,"_S",i,".bismark.DSS.CpG.txt")
    dat.list[[i]]=read.table(spl,header=F)
    colnames(dat.list[[i]])=c("chr",     "pos",     "N",       "X")
    }

BSobj = makeBSseqData( dat.list,c("D1M1","D1M2","D1M3","D1M4","D1M5","D1M6","D1M7","D1M8","D1M9","D1M10","D1M11","D1M12") )
dmlTest = DMLtest(BSobj, group2=c("D1M1","D1M2","D1M3","D1M4","D1M5","D1M6","D1M11"), group1=c("D1M7","D1M8","D1M9","D1M10","D1M12"),smoothing=TRUE)
dmls = callDML(dmlTest, delta=0.1, p.threshold=0.001)
write.table(dmls,"DML_CrevsN_12_delta0.1_p0.001.txt",sep="\t",row.name=FALSE,quote=F)
dmrs = callDMR(dmlTest,delta=0.1, p.threshold=0.05)
write.table(dmrs,"DMR_CrevsN_12_delta0.1_p0.05.txt",sep="\t",quote=F,row.name=FALSE)

I used the CpG counts from bismark. Then I found there were quite a few non-CG sites in the result of the DML file, which is baffling.I wonder how could certain sites not contained in the input files show up? Also, I used the same code without the "smoothing" option. It turned out no "smoothing" fixed this problem. 
Could you please help me with this issue?

Thank you,

Yuxiang Li

**Comment by haowulab** [comment]
DSS doesn't check whether a site is CG or nonCG. it completely depends on the inputs. The only possibility is that there are nonCG sites in the input. DSS cannot "make up" sites.

**Comment by Yuxinagli** [comment]
Thank you for the reply. I think it's from the methylation calling. but somehow, smooth increasd the rate of confounded DML calling  of non-CG sites.
