### ISSUE TITLE
how to get pvalues from callDMR function ? 

### ISSUE THREAD

**Issue by emrgt** [haowulab/DSS#24]

**Comment by haowulab** [comment]
Do you still have this question? Seems you have closed the issue. callDMR does not return p-values. In DMR calling, the statistical test is perform for each CpG, and then the significant CpG are merged into regions. It is very difficult to get p-values at the region-level, based on the site level test results (p-values or FDR). This is a difficult question for all types of genome-wide assays such as the ChIP-seq. so I rather not to report a DMR-level p-value if it’s not accurate

**Comment by emrgt** [comment]
Thank you for you answer, 
Indeed I found another way to deal with the issue in the mean time.
