### ISSUE TITLE
Feature request: Using pre-computed smoothed values to run DML

### ISSUE THREAD

**Issue by zroger49** [haowulab/DSS#30]
Hello! 
I'm working with a WGBS dataset with 10 samples (5 control + 5 experimental group) and around 58 000 000 sites (27 000 000 or so after filtering). I started to explore this data by smoothing the values with the BSmooth package and performing PCA. Due to the limitation in computational resources and memory, the smoothing took ~ 30 hours or so. 

Now I would like to compare the methylation levels among two groups (possibly using several models adjusting for different sets of covariates). 

Is it possible to use these precomputed smoothing estimations with DSS DMLtest? From my understanding of this package, skipping this step would improve computations speed by a lot.

Best, 
Rogério

**Comment by haowulab** [comment]
You don't need to use BSmooth to smooth them. DSS implements a much faster smoothing procedure which produces very similar results to BSmooth.

**Comment by zroger49** [comment]
Hi! Thanks for your response,
