### ISSUE TITLE
error with DMLtest in DSS (DNA methylation analysis)

### ISSUE THREAD

**Issue by shaghayeghsoudi** [haowulab/DSS#45]
Hi DSS developers.
Thanks so much for the package. We have started using DSS to find DML/DMR for our RRBS data obtained from normal, primary and relapse sarcoma human tumors.

For now I am running DSS for two-group comparisons (for example to find DMLs/DMRs between Normal and primary tumors).

I should mentioned the number of replicates are not equal. For example I have 110 primary tumors and only 70 normal samples.
When I run DML test with the following code

`dmlTest <- DMLtest(BSobj, group1=groupNormal, group2=groupPrimary, smoothing=TRUE)`

I keep getting this error message:

```
In shrk.phi[ix] <- shrk.phi2 :
 number of items to replace is not a multiple of replacement length
```

I do not know where the error is coming from. I believe I do not have any "NA" in my data set.
So I wanted to ask is there any clue on why I am getting this error message?

Thanks you very much

**Comment by haowulab** [comment]
Hmm, we never encountered this problem before. Without debugging it's very difficult for me to figure out. Does this happen when analyzing a particular chromosome?

**Comment by shaghayeghsoudi** [comment]
Hi, thanks for your reply. I am analyzing all chromosomes together. But when I subset the data (for example the fist 10K positions) it goes fine. But it happens when I take large subset such as 100K.
Is there any chance I could share subset of my samples with you to have a look??  I have checked all possible scenarios that may cause this error but have not found anything so far. Thank you very much
