### ISSUE TITLE
question about constructing hypothesis test ( DMLtest.multiFactor)

### ISSUE THREAD

**Issue by shaghayeghsoudi** [haowulab/DSS#47]
I used DSS for our RRBS methylation data so far for tea-group comparison only. I'd like to expand the analysis a bit. We have three tissue types or groups (normal, before treatment and after treatment) and we just want to find DMLs/DMRs between these three groups.
By reading the manual I understood I can use "Hypothesis testing in general experimental design" 

DMLfit = DMLfit.multiFactor(BSobj, design=design, formula=~tissue_type)

followed by 

DMLtest = DMLtest.multiFactor(DMLfit, term="tissue_typ")

I just wanted to make sure my understanding is correct and this is the right way of finding DMLs between three groups?
I appreciate of you could provide any advice.
Thanks

**Comment by haowulab** [comment]
Yes this is correct.

**Comment by shaghayeghsoudi** [comment]
thank you
