### ISSUE TITLE
Calling DMRs with strand informations

### ISSUE THREAD

**Issue by pterzian** [haowulab/DSS#8]
Hello,

Is it possible to take in account the strand information when calling DMLs or DMRs ?
I was able to create BSseq objects with a strand column but I don't see a strand column in the `dmrs` table.

Paul

**Comment by haowulab** [comment]
Paul, 

DSS doesn't consider strand information. But you can separate the counts by strand and create two BSseq objects then call DMR separately. 

Hao

**Comment by pterzian** [comment]
Great idea !
Thank you
